
# x=123
# for i in x:
#     print(i)

Answer: Since x is not an iterator, error is throwing.for
=================================================================
#i=0
#while i<5:
#    print(i)
#    i+=1
#    if i==3:
#        break
#    else:
#        print("error")

Answer:
0
error
1
error
2
error
3
====================================================================
# count=0
# while True:
#     print(count)
#     count+=1
#     if count>=5:
#         break

Answer:
0
1
2
3
4
5



